export const myData = [
  {
    name: 'iPhone 14 Pro Max',
    desc: '6.7-inch OLED display, A16 Bionic chip, 128GB storage, 48MP triple camera',
    src: '/assets/phone-1.webp',
    price: 1099,
    brand: 'Apple',
    id: 1,
  },
  {
    name: 'Samsung Galaxy S23 Ultra',
    desc: '6.8-inch AMOLED display, Snapdragon 8 Gen 2, 256GB storage, 200MP quad camera',
    src: '/assets/phone-1.webp',
    price: 1199,
    brand: 'Samsung',
    specs:
      'Display Size: 55 inch, RAM: 4 TB, ROM: 500 TB, Display: Black & White',
    id: 2,
  },
  {
    name: 'Google Pixel 7 Pro',
    desc: '6.7-inch OLED display, Google Tensor G2, 128GB storage, 50MP dual camera',
    src: '/assets/phone-1.webp',
    price: 899,
    brand: 'Google',
    id: 3,
  },
  {
    name: 'OnePlus 11',
    desc: '6.7-inch AMOLED display, Snapdragon 8 Gen 2, 128GB storage, 50MP triple camera',
    src: '/assets/phone-1.webp',
    price: 799,
    brand: 'OnePlus',
    id: 4,
  },
  {
    name: 'Xiaomi 13 Pro',
    desc: '6.73-inch AMOLED display, Snapdragon 8 Gen 2, 256GB storage, 50MP triple camera',
    src: '/assets/phone-1.webp',
    price: 999,
    brand: 'Xiaomi',
    id: 5,
  },
  {
    name: 'Sony Xperia 1 IV',
    desc: '6.5-inch OLED display, Snapdragon 8 Gen 1, 512GB storage, 12MP triple camera',
    src: '/assets/phone-1.webp',
    price: 1199,
    brand: 'Sony',
    id: 6,
  },
  {
    name: 'Oppo Find X6 Pro',
    desc: '6.82-inch AMOLED display, Dimensity 9000, 256GB storage, 50MP triple camera',
    src: '/assets/phone-1.webp',
    price: 1099,
    brand: 'Oppo',
    id: 7,
  },
  {
    name: 'Huawei P50 Pro',
    desc: '6.6-inch OLED display, Kirin 9000, 256GB storage, 50MP quad camera',
    src: '/assets/phone-1.webp',
    price: 999,
    brand: 'Huawei',
    id: 8,
  },
];
